# Generated by Django 4.1.7 on 2023-03-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bids_count',
            field=models.IntegerField(default=0),
        ),
    ]
