# Generated by Django 4.1.7 on 2023-03-11 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_bids_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='first_price',
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_price',
            field=models.FloatField(max_length=12, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
