# Generated by Django 4.1.7 on 2023-03-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_bid_first_price_alter_auction_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
